In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import random
import collections
# 随机选择K个中心点
# 把每个数据点分配到离它最近的中心点
# 重新计算每类中的点到该类中心点距离的平均值
# 分配每个数据到它最近的中心点；
# 重复步骤3和4，直到所有的观测值不再被分配或是达到最大的迭代次数

In [2]:
# 载入数据
def loadData():
    iris = pd.read_csv("../iris.csv",header=None)
    k = len(iris[4].value_counts())
    lables = iris.iloc[:,4:].values.tolist()
    dataMat = np.array(iris.iloc[:,0:4].values.tolist())
    return k,dataMat,lables

In [3]:
# # 欧式距离
def distance(mat1,mat2):
    return np.sqrt(sum((mat1-mat2)**2))
# def distance(mat1,mat2):
#     diffMat = mat1 - mat2
#     sqDiffMat = diffMat**2
#     sqDistance = sqDiffMat.sum(axis = 1)
#     distance = sqDistance**0.5
#     return distance

In [4]:
def randomPoint(k):
    randomPointList = random.sample(range(0,150), k)
    return randomPointList

In [16]:
# 簇个数，数据集，最大迭代次数
def kMeans(maxTimes):
    # 载入数据
    k,dataMat,lables = loadData()
    # 数据集长度
    length = dataMat.shape[0]
    # 随机产生的最开始的点
    cPoints = randomPoint(k)
    # 第一次分配
    classes = []
    for i in range(0,k):
        classes.append([])
        
    for i in range(0,length):
        if( i in cPoints):
            continue 
        distanceList = []
        for x in cPoints:
            distanceList.append(distance(dataMat[i],dataMat[x]))
            max_index = distanceList.index(min(distanceList))
        classes[max_index].append(i)
    
    # 迭代次数
    count = 0
    point = np.zeros( (k,4) )
    
    while(count < maxTimes):
        pointTemp = np.zeros( (k,4) )
        for i in range(0,3):
            for index in classes[i]:
                pointTemp[i] += dataMat[index]
            length = float(len(classes[i]))
            pointTemp[i]/=length
            
            
            
            
            
        # 如果收敛
        if(pointTemp.all() == point.all()):
            break
        else:
            point = pointTemp
            count+=1
            
            
            
    # 票选出最终结果
    result = []
    for i in range(0,3):
        frequency = {}
        for index in classes[i]:
            if lables[index][0] not in frequency:
                frequency[lables[index][0]] = 1
            else:
                frequency[lables[index][0]] += 1
        result.append(max(frequency,key=frequency.get))
        
    return result,point,count

In [17]:
k,dataMat,lables = loadData()
kMeans(119)

[[6.07631579 2.81315789 4.66052632 1.56710526]
 [4.99038462 3.34807692 1.56923077 0.29038462]
 [7.16842105 3.16842105 6.06842105 2.15263158]]
[[6.07631579 2.81315789 4.66052632 1.56710526]
 [4.99038462 3.34807692 1.56923077 0.29038462]
 [7.16842105 3.16842105 6.06842105 2.15263158]]


(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica'],
 array([[6.07631579, 2.81315789, 4.66052632, 1.56710526],
        [4.99038462, 3.34807692, 1.56923077, 0.29038462],
        [7.16842105, 3.16842105, 6.06842105, 2.15263158]]),
 1)

In [7]:
np.zeros( (k,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
point1 = np.zeros( (k,4) )
point2 = np.zeros( (k,4) )

In [9]:
print(point1 == point2)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [10]:
if(point1.any() == point2.any()):
    print("222")

222
